server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chuanzhidongping/config83.git
  rabbitmq:
    host: 192.168.2.133
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh  #暴露触发消息总线的地址