server:
  port: 6868
spring:
  application:
    name: tensquare-eureka
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: false #是否从Eureka中获取注册信息
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/  #Eureka客户端与Eureka服务端进行交互的地址